/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import java.util.*;
import oberon.analysis.*;

@SuppressWarnings("nls")
public final class ABegstat extends PBegstat
{
    private TBegintxt _begintxt_;
    private final LinkedList<TSptxt> _sptxt_ = new LinkedList<TSptxt>();
    private PStatementsequence _statementsequence_;

    public ABegstat()
    {
        // Constructor
    }

    public ABegstat(
        @SuppressWarnings("hiding") TBegintxt _begintxt_,
        @SuppressWarnings("hiding") List<TSptxt> _sptxt_,
        @SuppressWarnings("hiding") PStatementsequence _statementsequence_)
    {
        // Constructor
        setBegintxt(_begintxt_);

        setSptxt(_sptxt_);

        setStatementsequence(_statementsequence_);

    }

    @Override
    public Object clone()
    {
        return new ABegstat(
            cloneNode(this._begintxt_),
            cloneList(this._sptxt_),
            cloneNode(this._statementsequence_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABegstat(this);
    }

    public TBegintxt getBegintxt()
    {
        return this._begintxt_;
    }

    public void setBegintxt(TBegintxt node)
    {
        if(this._begintxt_ != null)
        {
            this._begintxt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._begintxt_ = node;
    }

    public LinkedList<TSptxt> getSptxt()
    {
        return this._sptxt_;
    }

    public void setSptxt(List<TSptxt> list)
    {
        this._sptxt_.clear();
        this._sptxt_.addAll(list);
        for(TSptxt e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PStatementsequence getStatementsequence()
    {
        return this._statementsequence_;
    }

    public void setStatementsequence(PStatementsequence node)
    {
        if(this._statementsequence_ != null)
        {
            this._statementsequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementsequence_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._begintxt_)
            + toString(this._sptxt_)
            + toString(this._statementsequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._begintxt_ == child)
        {
            this._begintxt_ = null;
            return;
        }

        if(this._sptxt_.remove(child))
        {
            return;
        }

        if(this._statementsequence_ == child)
        {
            this._statementsequence_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._begintxt_ == oldChild)
        {
            setBegintxt((TBegintxt) newChild);
            return;
        }

        for(ListIterator<TSptxt> i = this._sptxt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TSptxt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._statementsequence_ == oldChild)
        {
            setStatementsequence((PStatementsequence) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
