/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AListnoneFieldlist extends PFieldlist
{
    private TSptxt _sptxt_;

    public AListnoneFieldlist()
    {
        // Constructor
    }

    public AListnoneFieldlist(
        @SuppressWarnings("hiding") TSptxt _sptxt_)
    {
        // Constructor
        setSptxt(_sptxt_);

    }

    @Override
    public Object clone()
    {
        return new AListnoneFieldlist(
            cloneNode(this._sptxt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListnoneFieldlist(this);
    }

    public TSptxt getSptxt()
    {
        return this._sptxt_;
    }

    public void setSptxt(TSptxt node)
    {
        if(this._sptxt_ != null)
        {
            this._sptxt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sptxt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sptxt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sptxt_ == child)
        {
            this._sptxt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sptxt_ == oldChild)
        {
            setSptxt((TSptxt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
