/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import java.util.*;
import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AProcedurecall extends PProcedurecall
{
    private TIdentifier _identifier_;
    private final LinkedList<PActualparams> _actualparams_ = new LinkedList<PActualparams>();

    public AProcedurecall()
    {
        // Constructor
    }

    public AProcedurecall(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<PActualparams> _actualparams_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setActualparams(_actualparams_);

    }

    @Override
    public Object clone()
    {
        return new AProcedurecall(
            cloneNode(this._identifier_),
            cloneList(this._actualparams_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedurecall(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PActualparams> getActualparams()
    {
        return this._actualparams_;
    }

    public void setActualparams(List<PActualparams> list)
    {
        this._actualparams_.clear();
        this._actualparams_.addAll(list);
        for(PActualparams e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._actualparams_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._actualparams_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PActualparams> i = this._actualparams_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PActualparams) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
