/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AProcedurebody extends PProcedurebody
{
    private PDeclarations _declarations_;
    private PProcedurebodystatements _procedurebodystatements_;
    private TEndtxt _endtxt_;

    public AProcedurebody()
    {
        // Constructor
    }

    public AProcedurebody(
        @SuppressWarnings("hiding") PDeclarations _declarations_,
        @SuppressWarnings("hiding") PProcedurebodystatements _procedurebodystatements_,
        @SuppressWarnings("hiding") TEndtxt _endtxt_)
    {
        // Constructor
        setDeclarations(_declarations_);

        setProcedurebodystatements(_procedurebodystatements_);

        setEndtxt(_endtxt_);

    }

    @Override
    public Object clone()
    {
        return new AProcedurebody(
            cloneNode(this._declarations_),
            cloneNode(this._procedurebodystatements_),
            cloneNode(this._endtxt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedurebody(this);
    }

    public PDeclarations getDeclarations()
    {
        return this._declarations_;
    }

    public void setDeclarations(PDeclarations node)
    {
        if(this._declarations_ != null)
        {
            this._declarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarations_ = node;
    }

    public PProcedurebodystatements getProcedurebodystatements()
    {
        return this._procedurebodystatements_;
    }

    public void setProcedurebodystatements(PProcedurebodystatements node)
    {
        if(this._procedurebodystatements_ != null)
        {
            this._procedurebodystatements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procedurebodystatements_ = node;
    }

    public TEndtxt getEndtxt()
    {
        return this._endtxt_;
    }

    public void setEndtxt(TEndtxt node)
    {
        if(this._endtxt_ != null)
        {
            this._endtxt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endtxt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declarations_)
            + toString(this._procedurebodystatements_)
            + toString(this._endtxt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declarations_ == child)
        {
            this._declarations_ = null;
            return;
        }

        if(this._procedurebodystatements_ == child)
        {
            this._procedurebodystatements_ = null;
            return;
        }

        if(this._endtxt_ == child)
        {
            this._endtxt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declarations_ == oldChild)
        {
            setDeclarations((PDeclarations) newChild);
            return;
        }

        if(this._procedurebodystatements_ == oldChild)
        {
            setProcedurebodystatements((PProcedurebodystatements) newChild);
            return;
        }

        if(this._endtxt_ == oldChild)
        {
            setEndtxt((TEndtxt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
