/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class ARectypeType extends PType
{
    private PRecordtype _recordtype_;

    public ARectypeType()
    {
        // Constructor
    }

    public ARectypeType(
        @SuppressWarnings("hiding") PRecordtype _recordtype_)
    {
        // Constructor
        setRecordtype(_recordtype_);

    }

    @Override
    public Object clone()
    {
        return new ARectypeType(
            cloneNode(this._recordtype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARectypeType(this);
    }

    public PRecordtype getRecordtype()
    {
        return this._recordtype_;
    }

    public void setRecordtype(PRecordtype node)
    {
        if(this._recordtype_ != null)
        {
            this._recordtype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._recordtype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._recordtype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._recordtype_ == child)
        {
            this._recordtype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._recordtype_ == oldChild)
        {
            setRecordtype((PRecordtype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
