/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import java.util.*;
import oberon.analysis.*;

@SuppressWarnings("nls")
public final class ATypedecl extends PTypedecl
{
    private final LinkedList<PTypedeclaration> _typedeclaration_ = new LinkedList<PTypedeclaration>();

    public ATypedecl()
    {
        // Constructor
    }

    public ATypedecl(
        @SuppressWarnings("hiding") List<PTypedeclaration> _typedeclaration_)
    {
        // Constructor
        setTypedeclaration(_typedeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ATypedecl(
            cloneList(this._typedeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypedecl(this);
    }

    public LinkedList<PTypedeclaration> getTypedeclaration()
    {
        return this._typedeclaration_;
    }

    public void setTypedeclaration(List<PTypedeclaration> list)
    {
        this._typedeclaration_.clear();
        this._typedeclaration_.addAll(list);
        for(PTypedeclaration e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typedeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typedeclaration_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PTypedeclaration> i = this._typedeclaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTypedeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
