/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.analysis;

import oberon.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAPlusOperator(APlusOperator node);
    void caseAMinusOperator(AMinusOperator node);
    void caseAMultiplyOperator(AMultiplyOperator node);
    void caseADivOperator(ADivOperator node);
    void caseAModOperator(AModOperator node);

    void caseTInteger(TInteger node);
    void caseTPlus(TPlus node);
    void caseTMult(TMult node);
    void caseTMin(TMin node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTSemi(TSemi node);
    void caseEOF(EOF node);
}
