/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AExgrtExpressionoperator extends PExpressionoperator
{
    private TExgt _exgt_;

    public AExgrtExpressionoperator()
    {
        // Constructor
    }

    public AExgrtExpressionoperator(
        @SuppressWarnings("hiding") TExgt _exgt_)
    {
        // Constructor
        setExgt(_exgt_);

    }

    @Override
    public Object clone()
    {
        return new AExgrtExpressionoperator(
            cloneNode(this._exgt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExgrtExpressionoperator(this);
    }

    public TExgt getExgt()
    {
        return this._exgt_;
    }

    public void setExgt(TExgt node)
    {
        if(this._exgt_ != null)
        {
            this._exgt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exgt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exgt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exgt_ == child)
        {
            this._exgt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exgt_ == oldChild)
        {
            setExgt((TExgt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
