/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import java.util.*;
import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AIdentlist extends PIdentlist
{
    private TIdentifier _identifier_;
    private final LinkedList<PAndidentifier> _andidentifier_ = new LinkedList<PAndidentifier>();

    public AIdentlist()
    {
        // Constructor
    }

    public AIdentlist(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<PAndidentifier> _andidentifier_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setAndidentifier(_andidentifier_);

    }

    @Override
    public Object clone()
    {
        return new AIdentlist(
            cloneNode(this._identifier_),
            cloneList(this._andidentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentlist(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PAndidentifier> getAndidentifier()
    {
        return this._andidentifier_;
    }

    public void setAndidentifier(List<PAndidentifier> list)
    {
        this._andidentifier_.clear();
        this._andidentifier_.addAll(list);
        for(PAndidentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._andidentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._andidentifier_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PAndidentifier> i = this._andidentifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAndidentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
