/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AMoreterms extends PMoreterms
{
    private TPlusorminusoror _plusorminusoror_;
    private PTerm _term_;

    public AMoreterms()
    {
        // Constructor
    }

    public AMoreterms(
        @SuppressWarnings("hiding") TPlusorminusoror _plusorminusoror_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setPlusorminusoror(_plusorminusoror_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new AMoreterms(
            cloneNode(this._plusorminusoror_),
            cloneNode(this._term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreterms(this);
    }

    public TPlusorminusoror getPlusorminusoror()
    {
        return this._plusorminusoror_;
    }

    public void setPlusorminusoror(TPlusorminusoror node)
    {
        if(this._plusorminusoror_ != null)
        {
            this._plusorminusoror_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusorminusoror_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusorminusoror_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusorminusoror_ == child)
        {
            this._plusorminusoror_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusorminusoror_ == oldChild)
        {
            setPlusorminusoror((TPlusorminusoror) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
