/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class ANoneSelector extends PSelector
{

    public ANoneSelector()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANoneSelector();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoneSelector(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
