/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AOrPlusorminusoror extends PPlusorminusoror
{
    private TOrtxt _ortxt_;

    public AOrPlusorminusoror()
    {
        // Constructor
    }

    public AOrPlusorminusoror(
        @SuppressWarnings("hiding") TOrtxt _ortxt_)
    {
        // Constructor
        setOrtxt(_ortxt_);

    }

    @Override
    public Object clone()
    {
        return new AOrPlusorminusoror(
            cloneNode(this._ortxt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrPlusorminusoror(this);
    }

    public TOrtxt getOrtxt()
    {
        return this._ortxt_;
    }

    public void setOrtxt(TOrtxt node)
    {
        if(this._ortxt_ != null)
        {
            this._ortxt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ortxt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ortxt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ortxt_ == child)
        {
            this._ortxt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ortxt_ == oldChild)
        {
            setOrtxt((TOrtxt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
