/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AProcedurebodystatements extends PProcedurebodystatements
{
    private TBegintxt _begintxt_;
    private PStatementsequence _statementsequence_;

    public AProcedurebodystatements()
    {
        // Constructor
    }

    public AProcedurebodystatements(
        @SuppressWarnings("hiding") TBegintxt _begintxt_,
        @SuppressWarnings("hiding") PStatementsequence _statementsequence_)
    {
        // Constructor
        setBegintxt(_begintxt_);

        setStatementsequence(_statementsequence_);

    }

    @Override
    public Object clone()
    {
        return new AProcedurebodystatements(
            cloneNode(this._begintxt_),
            cloneNode(this._statementsequence_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedurebodystatements(this);
    }

    public TBegintxt getBegintxt()
    {
        return this._begintxt_;
    }

    public void setBegintxt(TBegintxt node)
    {
        if(this._begintxt_ != null)
        {
            this._begintxt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._begintxt_ = node;
    }

    public PStatementsequence getStatementsequence()
    {
        return this._statementsequence_;
    }

    public void setStatementsequence(PStatementsequence node)
    {
        if(this._statementsequence_ != null)
        {
            this._statementsequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementsequence_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._begintxt_)
            + toString(this._statementsequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._begintxt_ == child)
        {
            this._begintxt_ = null;
            return;
        }

        if(this._statementsequence_ == child)
        {
            this._statementsequence_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._begintxt_ == oldChild)
        {
            setBegintxt((TBegintxt) newChild);
            return;
        }

        if(this._statementsequence_ == oldChild)
        {
            setStatementsequence((PStatementsequence) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
