/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AReadprocStatement extends PStatement
{
    private PReadproc _readproc_;

    public AReadprocStatement()
    {
        // Constructor
    }

    public AReadprocStatement(
        @SuppressWarnings("hiding") PReadproc _readproc_)
    {
        // Constructor
        setReadproc(_readproc_);

    }

    @Override
    public Object clone()
    {
        return new AReadprocStatement(
            cloneNode(this._readproc_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReadprocStatement(this);
    }

    public PReadproc getReadproc()
    {
        return this._readproc_;
    }

    public void setReadproc(PReadproc node)
    {
        if(this._readproc_ != null)
        {
            this._readproc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._readproc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._readproc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._readproc_ == child)
        {
            this._readproc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._readproc_ == oldChild)
        {
            setReadproc((PReadproc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
