/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class ARecordSelector extends PSelector
{
    private PSelector _selector_;
    private TIdentifier _identifier_;

    public ARecordSelector()
    {
        // Constructor
    }

    public ARecordSelector(
        @SuppressWarnings("hiding") PSelector _selector_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setSelector(_selector_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new ARecordSelector(
            cloneNode(this._selector_),
            cloneNode(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecordSelector(this);
    }

    public PSelector getSelector()
    {
        return this._selector_;
    }

    public void setSelector(PSelector node)
    {
        if(this._selector_ != null)
        {
            this._selector_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._selector_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._selector_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._selector_ == child)
        {
            this._selector_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._selector_ == oldChild)
        {
            setSelector((PSelector) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
