/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AStatwhileStatement extends PStatement
{
    private PWhilestatement _whilestatement_;

    public AStatwhileStatement()
    {
        // Constructor
    }

    public AStatwhileStatement(
        @SuppressWarnings("hiding") PWhilestatement _whilestatement_)
    {
        // Constructor
        setWhilestatement(_whilestatement_);

    }

    @Override
    public Object clone()
    {
        return new AStatwhileStatement(
            cloneNode(this._whilestatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatwhileStatement(this);
    }

    public PWhilestatement getWhilestatement()
    {
        return this._whilestatement_;
    }

    public void setWhilestatement(PWhilestatement node)
    {
        if(this._whilestatement_ != null)
        {
            this._whilestatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whilestatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whilestatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whilestatement_ == child)
        {
            this._whilestatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whilestatement_ == oldChild)
        {
            setWhilestatement((PWhilestatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
