/* This file was generated by SableCC (http://www.sablecc.org/). */

package oberon.node;

import oberon.analysis.*;

@SuppressWarnings("nls")
public final class AWriteprocStatement extends PStatement
{
    private PWriteproc _writeproc_;

    public AWriteprocStatement()
    {
        // Constructor
    }

    public AWriteprocStatement(
        @SuppressWarnings("hiding") PWriteproc _writeproc_)
    {
        // Constructor
        setWriteproc(_writeproc_);

    }

    @Override
    public Object clone()
    {
        return new AWriteprocStatement(
            cloneNode(this._writeproc_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWriteprocStatement(this);
    }

    public PWriteproc getWriteproc()
    {
        return this._writeproc_;
    }

    public void setWriteproc(PWriteproc node)
    {
        if(this._writeproc_ != null)
        {
            this._writeproc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._writeproc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._writeproc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._writeproc_ == child)
        {
            this._writeproc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._writeproc_ == oldChild)
        {
            setWriteproc((PWriteproc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
